ExcelLua.Bangpai_Jiazurizhi={{"id","type","txt"},
key1={1,"创建帮派","<content><font color='#ffffff'>八方庆祝，</font><font color='#fff600'>@1</font><font color='#ffffff'>创建了帮派</font><font color='#ffa800'>@2</font><font color='#ffffff'>。</font></content>"},
key2={2,"成员加入","<content><font color='#ffffff'>欢迎新伙伴</font><font color='#fff600'>@1</font><font color='#ffffff'>加入帮派。</font></content>"},
key3={3,"成员离开","<content><font color='#ffffff'>咱</font><font color='#fff600'>@1</font><font color='#ffffff'>离开了帮派，带走了他贡献的活跃。</font></content>"},
key4={4,"公告修改","<content><font color='#ffffff'>咱</font><font color='#fff600'>@1</font><font color='#ffffff'>大人</font><font color='#ffa800'>@2</font><font color='#ffffff'>修改了公告。</font></content>"},
key5={5,"升职","<content><font color='#ffffff'>咱</font><font color='#fff600'>@1</font><font color='#ffffff'>将</font><font color='#ffa800'>@2</font><font color='#ffffff'>的职位提升为副帮主。</font></content>"},
key6={6,"降职","<content><font color='#ffffff'>咱</font><font color='#fff600'>@1</font><font color='#ffffff'>将</font><font color='#ffa800'>@2</font><font color='#ffffff'>降职了成帮众了。</font></content>"},
key7={7,"举办酒宴","<content><font color='#ffffff'>土豪大人</font><font color='#fff600'>@1</font><font color='#ffffff'>举办了一场</font><font color='#ffa800'>@2</font><font color='#ffffff'>酒宴。</font></content>"},
key8={8,"参加酒宴","<content><font color='#ffffff'>咱</font><font color='#fff600'>@1</font><font color='#ffffff'>参加了</font><font color='#ffa800'>@2</font><font color='#ffffff'>举办的酒宴。</font></content>"},
key9={9,"领取活跃度奖励","<content><font color='#ffffff'>咱</font><font color='#fff600'>@1</font><font color='#ffffff'>领取了</font><font color='#ffa800'>@2</font><font color='#ffffff'>活跃度奖励，大家加油。</font></content>"},
key10={10,"帮派排行进前3（保持不算变化才算）","<content><font color='#ffffff'>咱们的帮派一跃成为排名第</font><font color='#fff600'>@1</font><font color='#ffffff'>的大帮了！</font></content>"},
key11={11,"帮派升级","<content><font color='#ffffff'>咱帮派升级啦！现在是</font><font color='#fff600'>@1</font><font color='#ffffff'>级了，多亏大家的努力！</font></content>"},
key12={12,"帮派中功能开启","<content><font color='#ffffff'>新的功能</font><font color='#fff600'>@1</font><font color='#ffffff'>开启啦！</font></content>"},
key13={13,"帮主被弹劾","<content><font color='#ffffff'>咱</font><font color='#fff600'>@1</font><font color='#ffffff'>弹劾了</font><font color='#ffa800'>@2</font><font color='#ffffff'>，成为了大家的新帮主~</font></content>"}}